from __future__ import annotations

import os

from core.config import DEFAULT_DPI, DEFAULT_ICO_SIZES, DEFAULT_PDF_MODE, DEFAULT_QUALITY


BOT_TOKEN = os.getenv("BOT_TOKEN", "")

MAX_DOWNLOAD_MB = 20
MAX_UPLOAD_MB = 50

MAX_DOWNLOAD_BYTES = MAX_DOWNLOAD_MB * 1024 * 1024
MAX_UPLOAD_BYTES = MAX_UPLOAD_MB * 1024 * 1024

CONVERT_TIMEOUT_SECONDS = 120

__all__ = [
    "BOT_TOKEN",
    "MAX_DOWNLOAD_BYTES",
    "MAX_UPLOAD_BYTES",
    "CONVERT_TIMEOUT_SECONDS",
    "DEFAULT_DPI",
    "DEFAULT_ICO_SIZES",
    "DEFAULT_PDF_MODE",
    "DEFAULT_QUALITY",
]